### ISSUE TITLE
User space processes

### ISSUE THREAD

**Issue by ethandmd** [ethandmd/reedos#27]
- [x] create new process
- [x] tear down process
- [x] s-mode trap handler for userspace syscalls (`ecall`), process termination w/ error code
- [x] process address space memory layout + how to swap stack, pagetables for syscall from userspace

**Comment by TCCQ** [comment]
Depends on Address spaces, see #39

**Comment by TCCQ** [comment]
Minimal version does not have that dependency, and we will be using that for the moment.

**Comment by TCCQ** [comment]
Functional `scall`s now work as of 16178fc . Address spaces are not implemented and are tracked in another issue. Currently all page mapping is non-lazy. In addition dropping a `Process` struct will ensure that it is completely cleanup and returns all of its memory via `PhysPageExtent` usage.

**Comment by TCCQ** [comment]
Minimal viable product suitable for building on top of is now live as of 16178fc . Other issues track remaining related functionalities.
