### ISSUE TITLE
housekeeping 2

### ISSUE THREAD

**Issue by TCCQ** [ethandmd/reedos#31]
Pick on naming style for all the variables and getters from rust. Consider doing the rust half with a macro.

**Comment by ethandmd** [comment]
- [ ] Consistent linker variable names
- [ ] Grow per hart stack to 2 pages
- [ ] Add per priv mode stack page (+ guard)
- [ ] Refactor `pfree()` to run in O(1)
- [ ] Make linker symbol getter fns macros
- [ ] Make `walk()` helper bit shift macros into true macros or inline fns.
