### ISSUE TITLE
Containers

### ISSUE THREAD

**Issue by ethandmd** [ethandmd/reedos#5]
Need soon:
- [x] Balanced BST
- [x] Doubly Linked List

**Comment by ethandmd** [comment]
[nomicon](https://doc.rust-lang.org/nomicon/index.html)
[reference](https://doc.rust-lang.org/nomicon/index.html)

**Comment by TCCQ** [comment]
Until `palloc` supports contiguous multi-page allocation, vector based collections are not immedaitely viable. This can be added and possibly adjust `kalloc` to also support larger blocks. The other option would be to have vectors switch to page granularity when larger than a page.

**Comment by TCCQ** [comment]
My current understanding is that it is not possible in general to move out of a pointer/reference. It makes sense only when the underlying type is Copy. That means that we can't move out of `Karc` and `Kbox`. 

I am really not sure why this is the case? Like a function that consumes the Kbox and returns the content should be no less safe than creating a Kbox by moving a stack intermediate value into the box? Apparently the box one would normally use (in alloc)  has a compiiler hardcoded deref_move, but that is not generally applicable.

`alloc` providing `box`, `rc`, `arc` is not in std and could be used in nostd when hooked up to our allocator, although it doesn't know about our allocating assumptions. I am not sure if that's in the spirit or not.
