### ISSUE TITLE
Allocator

### ISSUE THREAD

**Issue by ethandmd** [ethandmd/reedos#6]
- [x] kernel memory map layout
- [x] kernel physical page allocator
- [x] kernel virtual memory allocator

**Comment by ethandmd** [comment]
allocator design ... bump allocator for simplicity?

**Comment by TCCQ** [comment]
Minimal viable is in associated branch. Does not completely conform to GlobalAlloc, but should be workable. See header comment.

**Comment by TCCQ** [comment]
The next refactor should fix realloc to attemp to expand the current entry before copying to a new alloc. This is faster in the best case and allows for edge cases where you could realloc in a memory strained system but the current implimentation would fail.

**Comment by TCCQ** [comment]
Work is now on the general-allocator branch. It currently supports requests less than a page. It rounds them up to a power of two and naturally aligns them. Dealloc is not efficient, but should do for now. We can fake page+ requests with palloc + VM to make it look contigous, but that should not be handled at this level. If we find we need that we can create another wrapper around this + palloc that will do VM management to fake contigiousness.
